version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: Statistic
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: Statistic
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    command: python get_data.py

volumes:
  postgres_data:
